### ISSUE TITLE
Qualified Exception.

### ISSUE THREAD

**Issue by kdub-nz** [gileCAD/Gile.AutoCAD.Extension#27]
Hi Gilles,
Error (active)	CS0104	'Exception' is an ambiguous reference between 'Autodesk.AutoCAD.Runtime.Exception' and 'System.Exception'	Gile.AutoCAD.R25.Extension	C:\Users\KDUB\source\repos\SharedAssemblies\Gile\Source\Gile.AutoCAD.Extension-master\Gile.AutoCAD.R25.Extension\ObjectIdExtension.cs	
//----
Error (active)	CS0104	'Exception' is an ambiguous reference between 'Autodesk.AutoCAD.Runtime.Exception' and 'System.Exception'	Gile.AutoCAD.R25.Extension	C:\Users\KDUB\source\repos\SharedAssemblies\Gile\Source\Gile.AutoCAD.Extension-master\Gile.AutoCAD.R25.Extension\RuntimeExtension.cs
/----

From my side I just  defined a using
`global using AcRx = Autodesk.AutoCAD.Runtime;`
and used the` AcRx.`  to qualify the exception.

//- - - - 
Of interest in 'RuntimeExtension.cs' 
The statement
`[CallerArgumentExpression("condition")] string? message = null)`

As recommended by my compiler, I have changed to 
`[CallerArgumentExpression(parameterName: nameof(condition))] string? message = null)`

Regards,
Kerry

**Comment by gileCAD** [comment]
Hi Kerry,
Thanks for reporting.
I do not have the "ambiguous reference" issues because there's none implicit using in my project.
